"""
Django settings for e_commerce_project project.

Generated by 'django-admin startproject' using Django 4.2.19.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

##########################################
load_dotenv()  # Loads .env into os.environ

##########################################
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

##########################################
# Security
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("Missing DJANGO_SECRET_KEY in environment.")

##########################################
DEBUG = True

# ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ["lennypro.com", "www.lennypro.com"]
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

##########################################
# Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory.apps.InventoryConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
]

##########################################
# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'e_commerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processor.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'e_commerce_project.wsgi.application'

##########################################
# Database

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",  # file will live in your project root
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("DATABASE_NAME"),
#         "USER": os.environ.get("DATABASE_USER"),
#         "PASSWORD": os.environ.get("DATABASE_PASSWORD"),
#         "HOST": os.environ.get("DATABASE_HOST", "db"),
#         "PORT": os.environ.get("DATABASE_PORT", "5432"),
#     }
# }

##########################################
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

##########################################
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

##########################################
# Static files
STATIC_URL = '/static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']  # development
STATIC_ROOT = BASE_DIR / 'staticfiles'  # production

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

##########################################
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##########################################
# Redis / Celery
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")

# Redis URLs for sessions and views
REDIS_SESSION_URL = os.environ.get("REDIS_SESSION_URL", "redis://redis:6379/3")
REDIS_VIEWS_URL = os.environ.get("REDIS_VIEWS_URL", "redis://redis:6379/4")

##########################################
# Cache configuration
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": CELERY_RESULT_BACKEND or "redis://redis:6379/0",
#         "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
#     },
#     "sessions": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": REDIS_SESSION_URL,
#         "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
#     },
#     "views": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": REDIS_VIEWS_URL,
#         "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
#     },
# }

##########################################
# Use database-backed sessions
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Use Redis cache for sessions
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "sessions"

##########################################
# Cart
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
CART_SESSION_ID = 'cart'

##########################################
# Email (console backend for now)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

##########################################
CSRF_TRUSTED_ORIGINS = [
    "https://lennypro.com",
    "https://www.lennypro.com",
]

##########################################
# Yookassa (Payment Service)
YOOKASSA_SECRET_KEY = os.environ.get('YOOKASSA_SECRET_KEY')
YOOKASSA_SHOP_ID = os.environ.get('YOOKASSA_SHOP_ID')
YOOKASSA_RETURN_URL = 'http://127.0.0.1:8000'  # for development
# YOOKASSA_RETURN_URL = 'https://lennypro.com'  # for production

